### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type std::length_error: vector

### ISSUE THREAD

**Issue by Colin97** [wildmeshing/fTetWild#11]
Thanks for the great work.

I was receiving the error when running the program:
libc++abi.dylib: terminating with uncaught exception of type std::length_error: vector

Do you have any idea what should I do?

Best,

[3.obj.zip](https://github.com/wildmeshing/fTetWild/files/4933419/3.obj.zip)

**Comment by isabellahuang** [comment]
Same error for me

**Comment by Yixin-Hu** [comment]
Hi, 

we are developing new features, which introduced a bug accidentally. We are fixing it. 

Please use our stable version on commit: 9235cd99c81aeca7bbd18ecf7691505d690b944f

**Comment by teseoch** [comment]
it was a stupid bug, it is now fixed
