### ISSUE TITLE
mpir.dll was not found

### ISSUE THREAD

**Issue by omgitsraven** [wildmeshing/fTetWild#19]
I'm building fTetWild on Windows, and after following the instructions here https://github.com/Yixin-Hu/TetWild/issues/44 I succeeded in producing an .exe, but then double-clicking that .exe produces the following error:

![image](https://user-images.githubusercontent.com/8540042/90581711-e7988600-e199-11ea-8b91-fec4b13b1a4f.png)

By looking through this thread https://github.com/wildmeshing/fTetWild/issues/12 I managed to find the required DLL in `C:\ProgramData\Anaconda3\pkgs\mpir-3.0.0-hec2e145_1\Library\bin`, and now the .exe seems to work, but this should probably be included in the build instructions

**Comment by teseoch** [comment]
Done!
