### ISSUE TITLE
Differences between output files?

### ISSUE THREAD

**Issue by omgitsraven** [wildmeshing/fTetWild#20]
The readme suggests that the .msh file produced by fTetWild is its "output"... but I was having a lot of trouble with the programs recommended for converting .msh files, so I took a look at some of the other files that fTetWild *also* outputs on every execution, but I'm not certain as to their contents...

from what I can tell (assuming an input file named `debug.stl`) :
- `debug.stl__sf.obj` and `debug.stl__tracked_surface.stl` are identical to `debug.stl_.msh`
- `debug.stl__simplify.off` and `debug.stl__cutting.stl` are identical to each other, but look rougher than the previous files

Is this a safe assumption, or are these results just a quirk of my input file?
i.e., if I'm struggling to convert the `_.msh` file to a format I can use, is it always safe to use the `__sf.obj` or `__tracked_surface.stl` file instead?

**Comment by teseoch** [comment]
the msh file is a *volumetric* tetrahedral mesh, the real output of the algorithm.
The obj/stl are * surface* only, that can be extracted from the msh.

If you dont like the binary msh, you can either use the option `--no-binary` or use the `-o` option and specify a .mesh file
