### ISSUE TITLE
Build fTetraWild without tbb library

### ISSUE THREAD

**Issue by hph73** [wildmeshing/fTetWild#22]
Hi Yixin,

I was trying to compile fTetWild without TBB library by setting the FLOAT_TETWILD_ENABLE_TBB option to OFF. However, after doing so I got quite a few error messages from cmake. It seems that TBB is required to build fast_winding_number, FloatTetwild_bin, FloatTetwild. Any clue how to fixed it?

Thanks,

Hao

**Comment by Yixin-Hu** [comment]
Hi,

Thanks for reporting the problem. It's fixed now. The code should work with FLOAT_TETWILD_ENABLE_TBB disabled.

**Comment by hph73** [comment]
Thanks:) I just confirmed that the problem has been solved.
