### ISSUE TITLE
Feature request: user-defined bounding box

### ISSUE THREAD

**Issue by hph73** [wildmeshing/fTetWild#24]
Hi,

I would like to define my own bounding box for tetrahedralization. I notice that bbox_min and bbox_max are provided in the input parameters but got overwritten with the following piece of code. Is it possible to add a flag in the input parameters to avoid the overwriting behavior?

```
        Vector3 min, max;
        get_bb_corners(params, input_vertices, min, max);
        
        mesh.params.bbox_min = min;
        mesh.params.bbox_max = max;
```

**Comment by Yixin-Hu** [comment]
HI,

For adding your own bbox, simply input the box with your model together instead of changing the code.

**Comment by hph73** [comment]
It makes sense. Thanks!
