### ISSUE TITLE
Input parameters manifold_surface and input_tags

### ISSUE THREAD

**Issue by hph73** [wildmeshing/fTetWild#25]
Hi,

I have difficulties in understanding the input parameters "manifold_surface" and "input_tags". 

(1) Is it a better choice to set manifold_surface to true since it guarantees a 2-manifold output? Why does the author set it to false by default?

(2) What's the meaning of  "input_tags" and how to use it?

Thanks!

**Comment by Yixin-Hu** [comment]
Hi,

(1) Manifold output tetmesh is not always necessary, so we don't set this flag as the default option.
(2) "--tag" ("input_tags") is for marking faces on different models for boolean operation.

**Comment by hph73** [comment]
Noted with thanks.
