### ISSUE TITLE
Regions and Boolean Operations

### ISSUE THREAD

**Issue by KeithBallard** [wildmeshing/fTetWild#26]
Hi,

First, fTetWild seems like an even better implementation of TetWild, which is saying a lot.  Great job!

I opened a related issue on TetWild's repo earlier today, and my motivation is just as I stated over there.  Fundamentally, I am trying to figure out a way to take multiple triangulated manifolds, create a tetrahedralization of the union, but still be able to identify which region each resulting tetrahedron belongs to. (see figure below for an example of the overlapping manifolds)

![image](https://user-images.githubusercontent.com/19842971/98886364-ed80c900-2461-11eb-80e0-66a189150f64.png)

Same model with semi-transparency to make the point of intersections
![image](https://user-images.githubusercontent.com/19842971/98887403-ece93200-2463-11eb-9ce0-730ba3b343aa.png)

fTetWild does a great job tetrahedralizing the union (with better performance than TetWild), though I am still stuck trying to figure out how one might determine the corresponding region.  Ideally (to me) each tetrahedra would be colored by some combination of the tags of the manifolds that contain them (perhaps a hash of the list of manifold tags that contain them), though I do not understand you algorithm enough to grasp the feasibility or method to implement such a method.  I dabbled with the boolean operations to see if I could perform a sequence of operations on groups of manifolds at a time to create a tetrahedralization of each region, but I am encountering runtime errors for many of the operations.  So my question is two-fold:
1) Is there a method you see to assign each tetrahedra a region ID of sorts (as I asked on the TetWild repo) or
2) Can you point me to additional documentation on how the boolean operations and tags are expected to work? Perhaps I am misunderstanding how they ought to be used.

Thanks for your time!
Keith Ballard

**Comment by KeithBallard** [comment]
Update: I have read through most of the code and seen how to make the it work using the winding evaluated for each tag and bitsets!

![image](https://user-images.githubusercontent.com/19842971/98907316-a1974980-248c-11eb-9a95-9619d0e4eeab.png)

Once I realized you had implemented such a fast winding number evaluation, it was obvious to use that.  The integer formed by the bitset of whether a tetrahedron lies inside each manifold is label I am using.  I would be happy to clean up my code and submit a merge request if this of interest to you.

Currently, I have added an option --write-region-labels [PATH], and the file is simply an ASCII file like the tags each with a unsigned long long label for each tetrahedron.  Of course...this limits the bitset size to 64, so there must be 64 tags or fewer.  Honestly, I expect to exceed that, so perhaps a runtime check can be performed and based on the number of tags there are, the text file will either be unsigned long longs or just a string representation on each line (with a flag at the top of the file indicating which one)?

What are your thoughts?

**Comment by teseoch** [comment]
Dear @KeithBallard thank you for the comments.

We already have such a feature with boolean operations, here is how to use it:
1) You need to create a json file (e.g., `bool.json`) like this:
```json
{
    "operation": "union",
    "left": "<path-to-mesh1>",
    "right": {
        "operation": "union",
        "left": "<path-to-mesh2>",
        "right": "<path-to-mesh3>"
    }

}
```
2) Call use this command `./FloatTetwild_bin --csg bool.json -o <out.msh>`. If it doesn't work, you can try adding these flag `--no-binary --no-color`

**Comment by KeithBallard** [comment]
@teseoch,

Thank you for your response!  Ah, is that what the CSG tree refers to?  I saw the boolean function in the code and deduced how it works.  However, it does not do what I am suggesting.  It "could" be used to create the same effect, but the performance would be awful the way it is set up.  I was only mentioning boolean operations in the original post as a possible solution, though I found a better solution in the next comment.  What I am suggesting is some users like myself what to color each distinct region of the union of multiple manifolds.  fTetWild provides a fantastic union of the manifolds, it is just the step of labeling the tetrahedra after that is missing.  The way I implemented it in your code was reusing the tags, assuming each manifold has a tag in the range [0, # of manifolds - 1], looping over the tags to extract the surface and compute the winding number, flip the bit at the index of the "tag" in the bitset (which is of length # of manifolds), and label the tetrahedra with the resulting integer representation of the bit (albeit with overflow concerns as mentioned).

Unless I am missing something, fTetWild does not have this feature and has no way of accomplishing it (with a reasonable efficiency) through the current input options.  I am offering to make a merge request with my implementation if the development team thinks the feature would be something useful to others (I think it will).

Thanks,
Keith Ballard

**Comment by teseoch** [comment]
Why the performance would be awful?

What the csg code does is:
1) append all meshes after each other and assign the tags  (like your solution)
2) run ftetwild as is (so same runtime)
3) Use the csg to decide what to keep in the winding number (likely same performances)

**Comment by KeithBallard** [comment]
Ah, first I misunderstood that multiple booleans could performed on the same tetrahedralization result.  My comment on performance is then clearly incorrect.  Sorry about that.

However, I am still uncertain that would give me what I want.  Consider the test problem above with three manifolds (which is a lot less manifolds than I plan to use).  What I want is the list of tetrahedra separating those:

- Exclusively inside the red manifold
- Exclusively inside the blue manifold
- Exclusively inside the green manifold
- Exclusively inside the red and blue manifolds
- Exclusively inside the red and green manifolds
- Exclusively inside the blue and green manifolds
- Inside all three manifolds

I fail to see how to get that without a whole lot of boolean operations.  Am I missing something?

**Comment by teseoch** [comment]
uh, you want all combinations?

then yes, it can only detect what is inside all, and color each depending on the parent.
If you need all combinations, I would suggest changing how the colors are computed in the csg, so that we have the same interface

**Comment by KeithBallard** [comment]
I saw your comment as I was writing this, so I will finish my thought :)

Yes, I want all combinations.  The boolean operations need to achieve this would be:
   * Exclusively inside the red manifold: red \ (green U blue)
   * Exclusively inside the blue manifold: blue \ (green U red)
   * Exclusively inside the green manifold:  green \ (blue U red)
   * Exclusively inside the red and blue manifolds:  (blue ∩ red) \ green
   * Exclusively inside the red and green manifolds: (green ∩ red) \ blue
   * Exclusively inside the blue and green manifolds: (blue ∩ green) \ red
    *Inside all three manifolds: (blue ∩ red ∩ green)

That requires a lot more winding numbers that 21 evaluations of windings numbers of all tetrahedra and post-processing.  The bitset method I propose requires only 3 winding number evaluations, which is to my point of performance.  I originally had a misunderstanding, but the method I propose requires N evals vs N^3 evals, where N is the number of manifolds, which will make a big difference when N is on the order of 64 as I plan to do.

**Comment by KeithBallard** [comment]
I don't see how a modification of how coloring is performed for the csg would yield the same result.  Can you elaborate?

Right now, I added an option that runs a new function I wrote that computes the N winding numbers and evaluates the integer representation of the bitset for each tetrahedra and writes it to a file (each being on a new line).  How would you like it to work instead?

**Comment by teseoch** [comment]
there is line here:
https://github.com/wildmeshing/fTetWild/blob/0fce01a607382ef5ffb51610218d7cb5140d57a8/src/MeshImprovement.cpp#L1534

which could be changed with your trick with the bits (I think)

**Comment by KeithBallard** [comment]
To make sure we are on the same page.  I am suggesting the feature to output which combination of manifolds each tetrahedra falls in, but all tetrahedra would be output as a single mesh as fTetWild currently performs.

Are you suggesting to output each combination of manifolds as a separate mesh?  It would work the same, but personally, it is more convenient to have it all in one with labels to go with them.  Or am I misunderstanding?

**Comment by teseoch** [comment]
no, I am suggesting to change the color of the current export, instead of using max, using your trick.

**Comment by KeithBallard** [comment]
Ah I see. I thought about that too when I was implementing it.  My issue with the idea is that the color is a double, so this would further limit the number of manifolds to 54 or less.  Writing the bitset to a file at least allows 64 as an int or unlimited as a string.

**Comment by teseoch** [comment]
yes true, I still would try to keep the csg interface, you can output another file there.

the advantage of the color is that is it all integrated into one file

**Comment by KeithBallard** [comment]
I have not looked at the CSGTree part of the code too much, so forgive my naive question, but would that add a new field to the post-process part of the .msh file or would the label overwrite the current color assigned to the tetrahedra (which is quality?).  But, I see you point about integrating it into one file.  I wonder if they have an unsigned long long type of field in .msh files that could be used instead of a double.  I might look into that.

**Comment by teseoch** [comment]
when you use the csg, it will also output the parent id as color

**Comment by afshawnlotfi** [comment]
@KeithBallard Do you have your implementation somewhere for labeling. Right now trying to label fluid domains given some labels of the original mesh faces and looked like you had something working.

**Comment by mjx888** [comment]
An alternative method to handle the region labeling problem is the ray casting algorithm (point in polygon test). I tested my code (ray casting) in Matlab. Quite robust.

In this way, we don't need to modify ftetwild's code (like what KeithBallard did). 

My workflow is as follows.
1. Input: Surface 1 (V1, F1), Surface 2 (V2, F2), Surface 3 (V3, F3)
2. Generate mesh using ftetwild with union operation
3. Region labeling using ray casting algorithm. 

Output: vertices, elements, and region label vector for elements. For example, the intersected region of surface 1 and 2 is labeled as 4; the intersected region of surface 1, 2, and 3 is labeled as 7.
