### ISSUE TITLE
skip_simplify

### ISSUE THREAD

**Issue by hph73** [wildmeshing/fTetWild#27]
Hi,

A quick question about the parameter "skip_simplify". What's the benefits and drawback of setting skip_simplify to be true?

Thanks!

**Comment by Yixin-Hu** [comment]
Hi,

`skip_simplify` is for skipping the pre-processing step (as described in the paper). Turning it on makes the program slower. It's a flag for testing only. For regular users, I would not recommend using this flag.

**Comment by hph73** [comment]
Thanks for your quick reply.
