### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by trsh** [wildmeshing/fTetWild#3]
Can this be adapted for real time game isosurface generation and manipulation?

**Comment by Yixin-Hu** [comment]
Hi, I think it's not easy to adapt the algorithm to be real time.

**Comment by trsh** [comment]
@Yixin-Hu what would you suggest instead?

**Comment by Yixin-Hu** [comment]
You may try "Instant Field-Aligned Meshes".

**Comment by trsh** [comment]
@Yixin-Hu what about good old Cubical Marching Squares, Dual Contouring, Dual Marching cubes etc? Do newer algorithms outperform them in performance and quality?

**Comment by Yixin-Hu** [comment]
Marching algorithms are usually used for implicit surfaces and usually don't produce an output as smooth as other methods if an input surface triangle mesh is given. But I think grid-based method is fast.
