### ISSUE TITLE
error: downloading 'https://github.com/CLIUtils/CLI11/archive/v1.8.0.tar.gz' failed

### ISSUE THREAD

**Issue by 1044574240** [wildmeshing/fTetWild#30]
hello，I got a problem when I try to run the order "cmake .."
(It seems like the same problem  metioned in TetWild's Issuues which helped me inrunning TetWild but not the same in ftetwild)
here it is

[root@localhost build]# cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test IS_SUPPORTED_-Wall
-- Performing Test IS_SUPPORTED_-Wall - Success
-- Performing Test IS_SUPPORTED_-Wextra
-- Performing Test IS_SUPPORTED_-Wextra - Success
-- Performing Test IS_SUPPORTED_-pedantic
-- Performing Test IS_SUPPORTED_-pedantic - Success
-- Performing Test IS_SUPPORTED_-Wunused
-- Performing Test IS_SUPPORTED_-Wunused - Success
-- Performing Test IS_SUPPORTED_-Wno-long-long
-- Performing Test IS_SUPPORTED_-Wno-long-long - Success
-- Performing Test IS_SUPPORTED_-Wpointer-arith
-- Performing Test IS_SUPPORTED_-Wpointer-arith - Success
-- Performing Test IS_SUPPORTED_-Wformat-2
-- Performing Test IS_SUPPORTED_-Wformat-2 - Success
-- Performing Test IS_SUPPORTED_-Wuninitialized
-- Performing Test IS_SUPPORTED_-Wuninitialized - Success
-- Performing Test IS_SUPPORTED_-Wcast-qual
-- Performing Test IS_SUPPORTED_-Wcast-qual - Success
-- Performing Test IS_SUPPORTED_-Wmissing-noreturn
-- Performing Test IS_SUPPORTED_-Wmissing-noreturn - Success
-- Performing Test IS_SUPPORTED_-Wmissing-format-attribute
-- Performing Test IS_SUPPORTED_-Wmissing-format-attribute - Success
-- Performing Test IS_SUPPORTED_-Wredundant-decls
-- Performing Test IS_SUPPORTED_-Wredundant-decls - Success
-- Performing Test IS_SUPPORTED_-Werror-implicit
-- Performing Test IS_SUPPORTED_-Werror-implicit - Success
-- Performing Test IS_SUPPORTED_-Werror-nonnull
-- Performing Test IS_SUPPORTED_-Werror-nonnull - Success
-- Performing Test IS_SUPPORTED_-Werror-init-self
-- Performing Test IS_SUPPORTED_-Werror-init-self - Success
-- Performing Test IS_SUPPORTED_-Werror-main
-- Performing Test IS_SUPPORTED_-Werror-main - Success
-- Performing Test IS_SUPPORTED_-Werror-missing-braces
-- Performing Test IS_SUPPORTED_-Werror-missing-braces - Success
-- Performing Test IS_SUPPORTED_-Werror-sequence-point
-- Performing Test IS_SUPPORTED_-Werror-sequence-point - Success
-- Performing Test IS_SUPPORTED_-Werror-return-type
-- Performing Test IS_SUPPORTED_-Werror-return-type - Success
-- Performing Test IS_SUPPORTED_-Werror-trigraphs
-- Performing Test IS_SUPPORTED_-Werror-trigraphs - Success
-- Performing Test IS_SUPPORTED_-Werror-array-bounds
-- Performing Test IS_SUPPORTED_-Werror-array-bounds - Success
-- Performing Test IS_SUPPORTED_-Werror-write-strings
-- Performing Test IS_SUPPORTED_-Werror-write-strings - Success
-- Performing Test IS_SUPPORTED_-Werror-address
-- Performing Test IS_SUPPORTED_-Werror-address - Success
-- Performing Test IS_SUPPORTED_-Werror-int-to-pointer-cast
-- Performing Test IS_SUPPORTED_-Werror-int-to-pointer-cast - Success
-- Performing Test IS_SUPPORTED_-Werror-pointer-to-int-cast
-- Performing Test IS_SUPPORTED_-Werror-pointer-to-int-cast - Success
-- Performing Test IS_SUPPORTED_-Wno-unused-variable
-- Performing Test IS_SUPPORTED_-Wno-unused-variable - Success
-- Performing Test IS_SUPPORTED_-Wunused-but-set-variable
-- Performing Test IS_SUPPORTED_-Wunused-but-set-variable - Success
-- Performing Test IS_SUPPORTED_-Wno-unused-parameter
-- Performing Test IS_SUPPORTED_-Wno-unused-parameter - Success
-- Performing Test IS_SUPPORTED_-Wno-old-style-cast
-- Performing Test IS_SUPPORTED_-Wno-old-style-cast - Success
-- Performing Test IS_SUPPORTED_-Wshadow
-- Performing Test IS_SUPPORTED_-Wshadow - Success
-- Performing Test IS_SUPPORTED_-Wstrict-null-sentinel
-- Performing Test IS_SUPPORTED_-Wstrict-null-sentinel - Success
-- Performing Test IS_SUPPORTED_-Woverloaded-virtual
-- Performing Test IS_SUPPORTED_-Woverloaded-virtual - Success
-- Performing Test IS_SUPPORTED_-Wsign-promo
-- Performing Test IS_SUPPORTED_-Wsign-promo - Success
-- Performing Test IS_SUPPORTED_-Wstack-protector
-- Performing Test IS_SUPPORTED_-Wstack-protector - Success
-- Performing Test IS_SUPPORTED_-Wstrict-aliasing
-- Performing Test IS_SUPPORTED_-Wstrict-aliasing - Success
-- Performing Test IS_SUPPORTED_-Wstrict-aliasing-2
-- Performing Test IS_SUPPORTED_-Wstrict-aliasing-2 - Success
-- Performing Test IS_SUPPORTED_-Wswitch-default
-- Performing Test IS_SUPPORTED_-Wswitch-default - Success
-- Performing Test IS_SUPPORTED_-Wswitch-enum
-- Performing Test IS_SUPPORTED_-Wswitch-enum - Success
-- Performing Test IS_SUPPORTED_-Wswitch-unreachable
-- Performing Test IS_SUPPORTED_-Wswitch-unreachable - Failed
-- Performing Test IS_SUPPORTED_-Wcast-align
-- Performing Test IS_SUPPORTED_-Wcast-align - Success
-- Performing Test IS_SUPPORTED_-Wdisabled-optimization
-- Performing Test IS_SUPPORTED_-Wdisabled-optimization - Success
-- Performing Test IS_SUPPORTED_-Winvalid-pch
-- Performing Test IS_SUPPORTED_-Winvalid-pch - Success
-- Performing Test IS_SUPPORTED_-Wpacked
-- Performing Test IS_SUPPORTED_-Wpacked - Success
-- Performing Test IS_SUPPORTED_-Wno-padded
-- Performing Test IS_SUPPORTED_-Wno-padded - Success
-- Performing Test IS_SUPPORTED_-Wstrict-overflow
-- Performing Test IS_SUPPORTED_-Wstrict-overflow - Success
-- Performing Test IS_SUPPORTED_-Wstrict-overflow-2
-- Performing Test IS_SUPPORTED_-Wstrict-overflow-2 - Success
-- Performing Test IS_SUPPORTED_-Wctor-dtor-privacy
-- Performing Test IS_SUPPORTED_-Wctor-dtor-privacy - Success
-- Performing Test IS_SUPPORTED_-Wlogical-op
-- Performing Test IS_SUPPORTED_-Wlogical-op - Success
-- Performing Test IS_SUPPORTED_-Wnoexcept
-- Performing Test IS_SUPPORTED_-Wnoexcept - Success
-- Performing Test IS_SUPPORTED_-Wnon-virtual-dtor
-- Performing Test IS_SUPPORTED_-Wnon-virtual-dtor - Success
-- Performing Test IS_SUPPORTED_-Wdelete-non-virtual-dtor
-- Performing Test IS_SUPPORTED_-Wdelete-non-virtual-dtor - Success
-- Performing Test IS_SUPPORTED_-Werror-non-virtual-dtor
-- Performing Test IS_SUPPORTED_-Werror-non-virtual-dtor - Success
-- Performing Test IS_SUPPORTED_-Werror-delete-non-virtual-dtor
-- Performing Test IS_SUPPORTED_-Werror-delete-non-virtual-dtor - Success
-- Performing Test IS_SUPPORTED_-Wno-sign-compare
-- Performing Test IS_SUPPORTED_-Wno-sign-compare - Success
-- Performing Test IS_SUPPORTED_-Wnull-dereference
-- Performing Test IS_SUPPORTED_-Wnull-dereference - Failed
-- Performing Test IS_SUPPORTED_-fdelete-null-pointer-checks
-- Performing Test IS_SUPPORTED_-fdelete-null-pointer-checks - Success
-- Performing Test IS_SUPPORTED_-Wduplicated-cond
-- Performing Test IS_SUPPORTED_-Wduplicated-cond - Failed
-- Performing Test IS_SUPPORTED_-Wmisleading-indentation
-- Performing Test IS_SUPPORTED_-Wmisleading-indentation - Failed
-- Performing Test IS_SUPPORTED_-fno-omit-frame-pointer
-- Performing Test IS_SUPPORTED_-fno-omit-frame-pointer - Success
-- Performing Test IS_SUPPORTED_-fno-optimize-sibling-calls
-- Performing Test IS_SUPPORTED_-fno-optimize-sibling-calls - Success
CMake Error at .cache/cli11/cli11-download-prefix/src/cli11-download-stamp/downl                                                                                                                              oad-cli11-download.cmake:159 (message):
  Each download failed!

    error: downloading 'https://github.com/CLIUtils/CLI11/archive/v1.8.0.tar.gz'                                                                                                                               failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

         --- LOG END ---
         error: downloading 'https://github.com/CLIUtils/CLI11/archive/v1.8.0.ta                                                                                                                              r.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

         --- LOG END ---
         error: downloading 'https://github.com/CLIUtils/CLI11/archive/v1.8.0.ta                                                                                                                          r.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

         --- LOG END ---
         error: downloading 'https://github.com/CLIUtils/CLI11/archive/v1.8.0.ta                                                                                                                              r.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

         --- LOG END ---
         error: downloading 'https://github.com/CLIUtils/CLI11/archive/v1.8.0.ta                                                                                                                              r.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

         --- LOG END ---
         error: downloading 'https://github.com/CLIUtils/CLI11/archive/v1.8.0.ta                                                                                                                              r.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

         --- LOG END ---

gmake[2]: *** [cli11-download-prefix/src/cli11-download-stamp/cli11-download-dow                                                                                                                              nload] 错误 1
gmake[1]: *** [CMakeFiles/cli11-download.dir/all] 错误 2
gmake: *** [all] 错误 2
CMake Error at cmake/DownloadProject.cmake:179 (message):
  Build step for cli11 failed: 2
Call Stack (most recent call first):
  cmake/FloatTetwildDownloadExternal.cmake:15 (download_project)
  cmake/FloatTetwildDownloadExternal.cmake:53 (float_tetwild_download_project)
  cmake/FloatTetwildDependencies.cmake:20 (float_tetwild_download_cli11)
  CMakeLists.txt:73 (include)

-- Configuring incomplete, errors occurred!
See also "/root/fTetWild/build/CMakeFiles/CMakeOutput.log".
See also "/root/fTetWild/build/CMakeFiles/CMakeError.log".

I'd be appreciated if i can get some advice. THANKS!!

**Comment by 1044574240** [comment]
https://github.com/Yixin-Hu/TetWild/issues/43#issuecomment-518966435 
should i do like this ? @Yixin-Hu

**Comment by 1044574240** [comment]
while,I made it on mac.
Any way ,thanks.

**Comment by teseoch** [comment]
The url is valid (just checked). From the error message `Protocol "https" not supported or disabled in libcurl` i doubt that https is not a valid protocol :) it is more likely that some security feature on mac has disabled that protocol in libcurl.

Anyhow, the comment you added is a valid walk-around.
