### ISSUE TITLE
Bounding Box Size

### ISSUE THREAD

**Issue by jonathanhestroffer** [wildmeshing/fTetWild#35]
Hi Yixin,

Thank you for this code! fTetWild runs very fast.

I was wondering if I could specify the size of the bounding box? The mesh created in this box is useful for me and I would like to control the size..

Best,
Jonathan

**Comment by Yixin-Hu** [comment]
Hi Jonathan,

You can input the model with a box. fTetWild will preserve all the faces of the model and the box. Or you can change the min and max points of the bounding box: https://github.com/wildmeshing/fTetWild/blob/master/src/FloatTetDelaunay.cpp#L40-L44

Hope this helps,
Yixin
