### ISSUE TITLE
Inquiring input mesh used in the paper

### ISSUE THREAD

**Issue by Rgtemze** [wildmeshing/fTetWild#4]
Hi,
Before all, fTetWild is much faster than regular TetWild and we are making use of this version, thank you for that.
You have mentioned an input mesh (shown below) with 93 million vertices in your paper. Is it possible that you can refer us to it so that we can use it too?
![image](https://user-images.githubusercontent.com/8372277/74676999-5fc0c780-51c8-11ea-9214-bbce803bb2f3.png)

Sincerely.

**Comment by Yixin-Hu** [comment]
Unfortunately not, you need to ask permission to ntopology (https://ntopology.com/) to use it.

**Comment by Rgtemze** [comment]
Hi,
We have obtained a permission from ntopology to use that model. We could provide you with the confirmation email if you would like to. How should we proceed?
Sincerely.

**Comment by Yixin-Hu** [comment]
Hi,

You can ask ntopology to send you the model directly or forward the related emails to me (yixin.hu@nyu.edu) and I can send you the model.
