### ISSUE TITLE
How to use Boolean operation?

### ISSUE THREAD

**Issue by glovelfan** [wildmeshing/fTetWild#40]
Hi:

Thanks for the fTetWild. It is amazing! 

I want to use the Boolean operation to get the intersection of a cube and a torus. I used the command line in Windows "./FloatTetwild_bin -i cube.obj --tag torus.obj --op 1 -o res.msh". However, it gave me an error message as "Abnormal program termination: function terminate() was called". Is there anything wrong with the command line? Thank you!
![Image 3](https://user-images.githubusercontent.com/47479688/130264905-72ab9204-9362-4615-994a-4258f8c4cee4.png)
[model.zip](https://github.com/wildmeshing/fTetWild/files/7022929/model.zip)

**Comment by Yixin-Hu** [comment]
Hi,

To use Boolean function of fTetWild, you need to combine the meshes into one mesh file and input it with `-i`. Then, give each face of the input mesh an integer tag (in a single row, faces in the same component have the same tag) in a text file and input it with the option `--tag`.

Examples can be found here: https://github.com/wildmeshing/fTetWild#dataset, Figures in the paper.

Hope this helps,
Yixin

**Comment by glovelfan** [comment]
Thanks for the reply. That's super useful!

Regards
Linxu
