### ISSUE TITLE
A problem about optimizing

### ISSUE THREAD

**Issue by tyc1998** [wildmeshing/fTetWild#46]
Hello, professor!
I recently found an issue when using this code, the code doesn't seem to remove the mesh outside the geometry in advance before optimizing the mesh. This leads to a huge increase in the time cost and space cost of mesh optimization, after all, most people only want the mesh inside the geometry. I counted the changes in the number of grids before and after filter_outside, which further confirmed my judgment.
I would like to ask if my problem is real, and if so, I would like to optimize this problem to improve the efficiency of the code.
I really hope you can give me some information about this.

**Comment by Yixin-Hu** [comment]
Hi,

This is not a problem but a part of the algorithm. This is for avoiding global self-intersection and for models with open shells (no volume properly defined), though it sacrifices efficiency. For more details, please check our paper.

**Comment by tyc1998** [comment]
My bad! It seems that I am missing some parts in the algorithm. I think I'll pay more attention to the details this time around. Thanks for your help.

**Comment by Yixin-Hu** [comment]
no problem
