### ISSUE TITLE
Source code is incomplete

### ISSUE THREAD

**Issue by Const-me** [wildmeshing/fTetWild#52]
A few functions in the source code look like they were generated by some tool from something else, maybe from symbolic math.

Specifically, they are `AMIPS_energy_aux`, `AMIPS_jacobian`, and `AMIPS_hessian`. I don’t think people write [C++ code like that](https://github.com/wildmeshing/fTetWild/blob/master/src/LocalOperations.cpp#L1186-L1455).

Could you please open the actual source of that code, as opposed to output of a code generator?

Thanks in advance.

**Comment by Yixin-Hu** [comment]
Hi,

We use sympy to auto-generate the C code to calculate the energy value and it's jacobian and hessian https://www.sympy.org/en/index.html
