### ISSUE TITLE
Is it possible to make the output mesh hollow?

### ISSUE THREAD

**Issue by IwakuraRein** [wildmeshing/fTetWild#59]
Hi. I am wondering if this tool is capable of, instead of fulfilling the mesh's interior, generating a "surface" mesh with a adjustable thickness parameter?

**Comment by Yixin-Hu** [comment]
Hi,

fTetWild is not designed for solving this problem so it cannot be used for this. Maybe you can try cleaning a surface mesh with fTetWild and then offsetting the surface.
