### ISSUE TITLE
Surface information output

### ISSUE THREAD

**Issue by jiaruily** [wildmeshing/fTetWild#60]
Can I get the surface information of the output mesh? For example, surface triangles.
I see __sf.obj, but I want triangles with the same vertex index as in the mesh (.msh) file.

**Comment by Yixin-Hu** [comment]
Hi,

If you want the surface mesh of the output tetmesh with the vertex indices unchanged, then you need to output all the vertices of the tetmesh to the surface mesh (so there will be isolated vertices in the interior), which should be easy to do.  You need to write a script to process the output tetmesh.
