### ISSUE TITLE
cube and cylinder "touching"

### ISSUE THREAD

**Issue by gbettega** [wildmeshing/fTetWild#64]
Hello,
a simple question: a cube and a cylinder touch.
Is it possible to: compute the mesh of the (non manifold) union using the triangulation of the non manifold union
and distinguish the tehreahedra of the two volume grids?
The mesh should be conformal at the interfacece.
How to using a fTetwild command line? (Or C++ code)
I attached some pictures.
Ciao
Grazie mille
Giovanni

geometry

![pic00](https://github.com/wildmeshing/fTetWild/assets/19689741/cdc6ed0e-efca-465f-a1a9-74257665ed13)

triangulation
![pic02](https://github.com/wildmeshing/fTetWild/assets/19689741/06854753-5733-465e-8e84-2b7d8c7f6cde)

mesh (not done with ftetwild)
![pic03](https://github.com/wildmeshing/fTetWild/assets/19689741/6598b9b5-c6d3-4513-80f7-5702ee0f7643)

**Comment by Yixin-Hu** [comment]
Hi,

The simplest solution to try first is to combine the cylinder and the cube into a single mesh file and input it to fTetWild (using `--input` only would work). The interface of the cylinder and the cube would be preserved by the algorithm. To separate the output tets for the two objects, you can check if the centers of the tets inside certain object.

**Comment by gbettega** [comment]
Thank you very much Yixin
this is exactly the solution I adopted some days ago: indeed I was writing for sharing it: Some details:
1) the two - initially separated, distinct - solids (step file) are loaded into a viewer using an OpenCascade step reader
2) a non-manifold solid is created using the BOPAlgo_Builder class. In the resulting non-maniforld the base of the cylinder is a shared face
3) the triangulation of the composite solid is created using an OpenCascade class (BRepMesh_IncrementalMesh)
4) fTwtWild creates the tetrahedralization of the triangle soup (in the example I posted the soup is a watertight triangulation)
5) the barycenter of each tetrahedron is computed,: a tetrahedron "belongs" to a solid if the winding number of its center of mass, with respect to the triangulation of that solid, is greater than, say 0.5 (for problematic, non watertight, triangulations)
I attach a picture of a results, with a mesh refinement also applied to one face and a segment.
Grazie mille
Giovanni


![pic04](https://github.com/wildmeshing/fTetWild/assets/19689741/c3a47226-694e-41ac-999c-7064ec1a7bbe)

![pic05](https://github.com/wildmeshing/fTetWild/assets/19689741/855907a5-57a5-4f7b-b1c6-1b0e8210d2b1)
