### ISSUE TITLE
Sizing field interface in Python wrappers for Anaconda?

### ISSUE THREAD

**Issue by erleben** [wildmeshing/fTetWild#8]
Hi,

Would it be possible to add this functionality to the python wrappers?

Best 

Kenny

**Comment by Yixin-Hu** [comment]
Sorry, I'm occupied by other work these days. I'll do it this weekend.

**Comment by Yixin-Hu** [comment]
I added the feature into c++ code and you can try it already. We are adding new features these weeks and will release the updated conda package soon with these features.

**Comment by teseoch** [comment]
Done!
